### PR TITLE
Declare command properties as notnull (#46)

### LINKED ISSUE #46: Make [ReactiveCommand] command properties notnull
**Is your feature request related to a problem? Please describe.**

Having the commands declared as nullable results in additional code to either suppress nullable warnings or to apply null-checks. Obviously the commands are only null when `InitializeCommands` has not been called, which is an obvious programming error.

**Describe the solution you'd like**

I'd like the command properties to no longer be defined as nullable. Preferably I'd also like them not to have a null value at all, see last paragraph for possible implementation.

**Describe alternatives you've considered**

N/A.

**Describe suggestions on how to achieve the feature**

Instead of relying on `InitializeCommands` to set the command properties, declare them using a defined backing field (which should probably have `[EditorBrowsable(false)]`:

```csharp
private ReactiveCommand<Unit, RepositoryStatus>? _refreshCommand;

public ReactiveCommand<Unit, RepositoryStatus> RefreshCommand
{
    get
    {
        return _refreshCommand ??= ReactiveCommand.CreateFromTask(Refresh);
    }
}

[ReactiveCommand]
private Task<RepositoryStatus> Refresh()
{
    throw new NotImplementedException();
}
```

### PR DESCRIPTION
**Pull request by mycroes**
**What kind of change does this PR introduce?**

Declare command properties as notnull, fixes #46.

**What is the current behavior?**

Command properties are declared nullable.

**What is the new behavior?**

Command properties are declared as not null, `InitializeCommands` is obsoleted.

**What might this PR break?**

**Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

This is my first ever contribution to a source generator. While everything seems to work, the current syntax is as follows:
```csharp
public ReactiveUI.ReactiveCommand<global::System.Reactive.Unit, global::System.Reactive.Unit> Test9AsyncCommand
{
    get
    {
        return _test9AsyncCommand ??= ReactiveUI.ReactiveCommand.CreateFromTask(Test9Async) ;;
    }
}
```

I was expecting arrow syntax since my latest modifications, but either the generated file isn't regenerated or my implementation is wrong.

### CODE REVIEW

**Comment by glennawatson** [comment]
In terms of seeing the arrow expression, Visual Studio caches the value internally from the first run. They did add a button "regenerate" but I haven't found it works reliably.

What I do is add a flag to my project `<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>` and this will cause the source generator each compile to output into the obj directory. You can then see the latest output there.

**Comment by mycroes** [comment]
Microsoft at some times never cease to amaze me... The arrow expression is working, because now on startup it generated once. However, if I turn on `EmitCompilerGeneratedFiles` I get the following error:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	CS0016	Could not write to output file 'C:\Users\mycro\Documents\Projects\ReactiveUI.SourceGenerators\src\ReactiveUI.SourceGenerators.Execute\obj\Debug\net8.0-windows\generated\ReactiveUI.SourceGenerators\ReactiveUI.SourceGenerators.IViewForGenerator\ReactiveUI.SourceGenerators.IViewForAttribute.g.cs' -- 'Could not find a part of the path 'C:\Users\mycro\Documents\Projects\ReactiveUI.SourceGenerators\src\ReactiveUI.SourceGenerators.Execute\obj\Debug\net8.0-windows\generated\ReactiveUI.SourceGenerators\ReactiveUI.SourceGenerators.IViewForGenerator\ReactiveUI.SourceGenerators.IViewForAttribute.g.cs'.'	ReactiveUI.SourceGenerators.Execute	C:\Users\mycro\Documents\Projects\ReactiveUI.SourceGenerators\src\ReactiveUI.SourceGenerators.Execute\CSC	1	
```

This is repeated 14 times for different files. My guess is the file path may be too long? This is a fairly clean Windows 11 install, didn't tocuh any long filename settings (yet).

**Comment by glennawatson** [comment]
> Microsoft at some times never cease to amaze me... The arrow expression is working, because now on startup it generated once. However, if I turn on `EmitCompilerGeneratedFiles` I get the following error:
> 
> ```
> Severity	Code	Description	Project	File	Line	Suppression State
> Error (active)	CS0016	Could not write to output file 'C:\Users\mycro\Documents\Projects\ReactiveUI.SourceGenerators\src\ReactiveUI.SourceGenerators.Execute\obj\Debug\net8.0-windows\generated\ReactiveUI.SourceGenerators\ReactiveUI.SourceGenerators.IViewForGenerator\ReactiveUI.SourceGenerators.IViewForAttribute.g.cs' -- 'Could not find a part of the path 'C:\Users\mycro\Documents\Projects\ReactiveUI.SourceGenerators\src\ReactiveUI.SourceGenerators.Execute\obj\Debug\net8.0-windows\generated\ReactiveUI.SourceGenerators\ReactiveUI.SourceGenerators.IViewForGenerator\ReactiveUI.SourceGenerators.IViewForAttribute.g.cs'.'	ReactiveUI.SourceGenerators.Execute	C:\Users\mycro\Documents\Projects\ReactiveUI.SourceGenerators\src\ReactiveUI.SourceGenerators.Execute\CSC	1	
> ```
> 
> This is repeated 14 times for different files. My guess is the file path may be too long? This is a fairly clean Windows 11 install, didn't touch any long filename settings (yet).

Yeah, if you turn on long file support it'll eliminate those.

**Review by ChrisPulman — APPROVED** [review]

**Comment by mycroes** [comment]
Thx @ChrisPulman. I was going to update docs, but didn't get to it today... Happy this is merged though, will make my life a bit easier again!

**Pull request merged**
